// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIInfo() {
  return window['go']['main']['App']['APIInfo']();
}

export function AlertInfo(arg1) {
  return window['go']['main']['App']['AlertInfo'](arg1);
}

export function CreateAlert(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAlert'](arg1, arg2, arg3);
}

export function DNSResolve(arg1) {
  return window['go']['main']['App']['DNSResolve'](arg1);
}

export function DNSReverse(arg1) {
  return window['go']['main']['App']['DNSReverse'](arg1);
}

export function DeleteAlert(arg1) {
  return window['go']['main']['App']['DeleteAlert'](arg1);
}

export function DeleteNotifier(arg1) {
  return window['go']['main']['App']['DeleteNotifier'](arg1);
}

export function DisableTrigger(arg1, arg2) {
  return window['go']['main']['App']['DisableTrigger'](arg1, arg2);
}

export function DomainInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DomainInfo'](arg1, arg2, arg3, arg4);
}

export function EditAlert(arg1, arg2) {
  return window['go']['main']['App']['EditAlert'](arg1, arg2);
}

export function EnableTrigger(arg1, arg2) {
  return window['go']['main']['App']['EnableTrigger'](arg1, arg2);
}

export function ExportCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2);
}

export function ExportJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportJSON'](arg1, arg2);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetNotifier(arg1) {
  return window['go']['main']['App']['GetNotifier'](arg1);
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function HostInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['HostInfo'](arg1, arg2, arg3);
}

export function ListAlertTriggers() {
  return window['go']['main']['App']['ListAlertTriggers']();
}

export function ListAlerts() {
  return window['go']['main']['App']['ListAlerts']();
}

export function ListFacets() {
  return window['go']['main']['App']['ListFacets']();
}

export function ListFilters() {
  return window['go']['main']['App']['ListFilters']();
}

export function ListNotifiers() {
  return window['go']['main']['App']['ListNotifiers']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListProtocols() {
  return window['go']['main']['App']['ListProtocols']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListQueries(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListQueries'](arg1, arg2, arg3);
}

export function ListScans() {
  return window['go']['main']['App']['ListScans']();
}

export function MyIP() {
  return window['go']['main']['App']['MyIP']();
}

export function QueryTags(arg1) {
  return window['go']['main']['App']['QueryTags'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function ScanStatus(arg1) {
  return window['go']['main']['App']['ScanStatus'](arg1);
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4);
}

export function SearchAll(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchAll'](arg1, arg2, arg3, arg4);
}

export function SearchCount(arg1, arg2) {
  return window['go']['main']['App']['SearchCount'](arg1, arg2);
}

export function SearchQueries(arg1, arg2) {
  return window['go']['main']['App']['SearchQueries'](arg1, arg2);
}

export function SearchTokens(arg1) {
  return window['go']['main']['App']['SearchTokens'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
