// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shodan} from '../models';

export function APIInfo():Promise<shodan.APIInfo>;

export function AlertInfo(arg1:string):Promise<shodan.Alert>;

export function CreateAlert(arg1:string,arg2:Array<string>,arg3:number):Promise<shodan.Alert>;

export function DNSResolve(arg1:string):Promise<Record<string, string>>;

export function DNSReverse(arg1:string):Promise<Record<string, Array<string>>>;

export function DeleteAlert(arg1:string):Promise<void>;

export function DeleteNotifier(arg1:string):Promise<void>;

export function DisableTrigger(arg1:string,arg2:string):Promise<void>;

export function DomainInfo(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<shodan.DomainResponse>;

export function EditAlert(arg1:string,arg2:Array<string>):Promise<shodan.Alert>;

export function EnableTrigger(arg1:string,arg2:string):Promise<void>;

export function ExportCSV(arg1:string,arg2:string):Promise<string>;

export function ExportJSON(arg1:string,arg2:string):Promise<string>;

export function GetAPIKey():Promise<string>;

export function GetNotifier(arg1:string):Promise<shodan.Notifier>;

export function HasAPIKey():Promise<boolean>;

export function HostInfo(arg1:string,arg2:boolean,arg3:boolean):Promise<shodan.HostResponse>;

export function ListAlertTriggers():Promise<Array<shodan.Trigger>>;

export function ListAlerts():Promise<Array<shodan.Alert>>;

export function ListFacets():Promise<Array<string>>;

export function ListFilters():Promise<Array<string>>;

export function ListNotifiers():Promise<shodan.NotifiersResponse>;

export function ListPorts():Promise<Array<number>>;

export function ListProtocols():Promise<Record<string, string>>;

export function ListProviders():Promise<Record<string, any>>;

export function ListQueries(arg1:number,arg2:string,arg3:string):Promise<shodan.QueriesResponse>;

export function ListScans():Promise<shodan.ScansListResponse>;

export function MyIP():Promise<string>;

export function QueryTags(arg1:number):Promise<shodan.TagsResponse>;

export function Scan(arg1:string):Promise<shodan.ScanResponse>;

export function ScanStatus(arg1:string):Promise<shodan.ScanStatus>;

export function Search(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<shodan.SearchResponse>;

export function SearchAll(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<Array<shodan.Banner>>;

export function SearchCount(arg1:string,arg2:string):Promise<shodan.SearchCountResponse>;

export function SearchQueries(arg1:string,arg2:number):Promise<shodan.QueriesResponse>;

export function SearchTokens(arg1:string):Promise<shodan.TokensResponse>;

export function SetAPIKey(arg1:string):Promise<void>;
